### ISSUE TITLE
Mac AppStore 好像有盗版盗用您的APP

### ISSUE THREAD

**Issue by Miku06** [imxieyi/waifu2x-mac#1]
https://itunes.apple.com/cn/app/waifu2x/id1387298406?mt=12

**Comment by imxieyi** [comment]
@Miku06 感谢提醒！

意料之中。就以国内开发商的尿性没人这么做我反而会觉得奇怪。

对于这种行为我是不在乎的，不然也不会选择MIT协议。至于他有没有遵守MIT协议发布应用就无从得知了。即使没有遵守就以国内的环境来说也没有什么办法。

如果真有人去买，就当他是在交智商税了。

就算是waifu2x原版也遇到过类似的事情，详情见[这个issue](https://github.com/nagadomi/waifu2x/issues/190)，最后也不了了之了。

以后对于这种项目我会慎重考虑开源的时机，尽量不给这种垃圾开发商赚智商税的机会。
