### ISSUE TITLE
Unable to resolve build file: XCBCore.BuildFile (namedReferencesCannotBeResolved) (in target 'waifu2x-mac-app')

### ISSUE THREAD

**Issue by martin-braun** [imxieyi/waifu2x-mac#11]
Hi,

thank you for your work, but it seems the app cannot be built: 

<img width="1251" alt="Screenshot 2019-04-09 at 22 34 18" src="https://user-images.githubusercontent.com/24259245/55833371-a7da7c80-5b17-11e9-8bb6-753d78b2e3b5.png">

I tried [some stuff to get around it](https://stackoverflow.com/a/51217831/1540350), but without luck. Have you tested building weifu2x in the latest Xcode?

Also, I think it would be nicer to not just publish the compiled CLI in the Release tab, but also the standalone App!

Thank you!

**Comment by imxieyi** [comment]
Does this issue still exist in Xcode 10.2.1? You can try running `./build.sh`.
