### ISSUE TITLE
Not an issue, just a suggestion.

### ISSUE THREAD

**Issue by Lukeade815** [imxieyi/waifu2x-mac#13]
There is a feature for recent Macs called "VideoToolBox," it's used in the recent Handbrake update and it uses hardware encoding/decoding to make it much much faster. https://developer.apple.com/documentation/videotoolbox
Maybe you could try to implement it into the software.

**Comment by imxieyi** [comment]
There is currently no plan to support videos. This library does not help with static image scaling.
