### ISSUE TITLE
Bit-depth support?

### ISSUE THREAD

**Issue by ArguingMeadows** [imxieyi/waifu2x-mac#16]
Is there going to be a feature in the future to support more than 24-bit png? I would like to feed it 32-bit images and have the bit depth retained.

**Comment by imxieyi** [comment]
If you mean alpha channel, it is already supported.

**Comment by ArguingMeadows** [comment]
Well, yes and no. So I have 32-bit pngs that don't have an alpha channel and if I sent them through, they come back as 24-bit. My work around right is to crop in Premiere to force an alpha channel out of a PNG sequence, but I was wondering if I could just send out a PNG without cropping.

**Comment by imxieyi** [comment]
If you mean something like [CGImageAlphaInfo.noneSkipFirst](https://developer.apple.com/documentation/coregraphics/cgimagealphainfo/noneskipfirst), it should be an easy fix.

**Comment by ArguingMeadows** [comment]
Is that a command I can add in the CLI?

**Comment by imxieyi** [comment]
Not yet. You can use some programs like imagemagick to convert 24 bit images to 32 bit.
