### ISSUE TITLE
Images of Size Smaller than Model Input Cause Crash

### ISSUE THREAD

**Issue by KurumiSerori** [imxieyi/waifu2x-mac#17]
Seems unable to process pictures on Catalina, neither App or CLI version.

**Comment by imxieyi** [comment]
Tried the latest one in Releases on 10.15.2 and it works fine. Tried to compile from source using Xcode 11.3 and it also works. Are you copying or linking to binary out of the bundle?

**Comment by KurumiSerori** [comment]
Hi there, I'm using Xcode 11.3 and the automatic script to build the app. I'm using symbolic link on the binary.
The app can launch until I hit the process button. Both app and CLI gives me an 'Illegal instruction: 4' signal.

The crash report of app can be found at [Ubuntu Paste](https://paste.ubuntu.com/p/Jk8tKMcmWD/).
I'm inexperienced with MacOS coding, hope this can help.

**Comment by imxieyi** [comment]
Did you try building from Xcode? Just try [Option B](https://github.com/imxieyi/waifu2x-mac#option-b-manual). Also, please try pre-built package from [releases](https://github.com/imxieyi/waifu2x-mac/releases).

**Comment by KurumiSerori** [comment]
I have tried to build the app from Xcode and also tested the pre-released version, this crash still exists. 
I followed the crash report and try to locate the problem, I think the app or cli tool always crash on this line of code in Waifu2x.in_pipeline within Waifu2x.run Module.

<img width="1792" alt="Xnip2020-01-28_20-33-05" src="https://user-images.githubusercontent.com/10769279/73264309-70a39c00-420d-11ea-8167-79d2f7184115.png">

**Comment by imxieyi** [comment]
Does this happen on all images? It looks like an image-specific issue. Please try a larger image.

**Comment by KurumiSerori** [comment]
You're right, seems the crash only occurs on small-sized images. The app works well with those larger ones.
As we have found the cause, I'm gonna closing this issue. Thanks for help.

**Comment by imxieyi** [comment]
This is still a bug. Waifu2x-ios store version contains a fix for this. I will back port this fix when I have time.

**Comment by KurumiSerori** [comment]
Fine, as your wish. :wink:
