### ISSUE TITLE
TIFF Support?

### ISSUE THREAD

**Issue by ArguingMeadows** [imxieyi/waifu2x-mac#18]
The iOS app supports importing TIFF images (and then turning them into PNG) but on the Mac side, there's no support whatsoever. I was wondering if we could see support for 16-bit TIFF images as import and export options.

**Comment by imxieyi** [comment]
Have you tried CLI version? I tried to use TIFF image as CLI input and there was no problem.

**Comment by ArguingMeadows** [comment]
Sorry for the very late reply, I have been using the CLI version and I always get back the same corrupt image that the app version spits out. 

Here are some sample files: https://drive.google.com/drive/folders/1cU93AhrVrqmBk_tGlagp1fOP9JLB9CkA?usp=sharing

Can't figure out why this happens.

**Comment by imxieyi** [comment]
Should be fixed in 24479f7.
