### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by pakoito** [imxieyi/waifu2x-mac#19]
After a `brew install` on High Sierra `v10.13.6` I'm finding a library that isn't linked, as per the title

```
λ MBP ~ → waifu2x --help                      
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/waifu2x
  Reason: image not found
[1]    93255 abort      waifu2x --help
```

```
λ MBP ~ → xcode-select -v    
xcode-select version 2349.
```

**Comment by imxieyi** [comment]
It looks like swift libraries cannot be located.

Can you try updating to v0.0.4? I uploaded a version with possible fix.

**Comment by pakoito** [comment]
Yeah, it works now :D What was it?

**Comment by imxieyi** [comment]
You can take a look at commit log if you are interested.

**Comment by pakoito** [comment]
Thanks!
