### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by chargeflux** [imxieyi/waifu2x-mac#2]
Hi! I was wonder if it is possible for you to make a CLI version of Waifu2x-mac because it would help with batch-processing. From looking at the code for the GUI, you call the function Waifu2x with the arguments 'img' and a predefined model when pressing the Process button. Unfortunately that is the extent of what I know about Swift and don't have the knowledge to make it into a CLI program.

I hope you can consider it or point me to how I could do it on my own. When I compiled Waifu2x_mac, I do get a UNIX executable in the framework but you can't run it from Terminal so that is probably not what is intended for. 

Thanks!

**Comment by imxieyi** [comment]
That's a great idea. I will implement it when I have time.

**Comment by imxieyi** [comment]
@CarbonFiberAnthem I have added a simple CLI version. You can compile and try it in the latest version on git.

**Comment by chargeflux** [comment]
I just needed to install the gem `xcodeproj` but the CLI version works great! Thanks for adding it :D
