### ISSUE TITLE
It always build failed.

### ISSUE THREAD

**Issue by fisheva** [imxieyi/waifu2x-mac#23]
After the first build, I seem to have deleted the build folder by mistake(Combined with 2# floor, I seem to have never built successfully). I want to use build.sh to build again, but after dragging build.sh to Terminal, it always only executes the last operation to delete all files.
<img width="840" alt="WX20200923-142310@2x" src="https://user-images.githubusercontent.com/17448419/93974453-6770cc00-fda8-11ea-8446-4936cda34bee.png">

How to use build.sh to rebuild APP?

**Comment by fisheva** [comment]
I changed a path to git clone this repository, and then dragged build.sh into Terminal, press the Return button, but it still always build failed and gave no reason.
![image](https://user-images.githubusercontent.com/17448419/93977705-7908a280-fdad-11ea-92fa-8b30ee378cf0.png)

My OS:  MacOS Catalina, version 10.15.6.    Xcode 12.2 beta.

In addition, I really don’t understand the meaning of build Option B. So I have been trying Option A.

**Comment by imxieyi** [comment]
Did you try to open Xcode (double click `waifu2x-mac.xcodeproj`) and build from the GUI?

**Comment by fisheva** [comment]
I opened 'waifu2x-mac.xcodeproj' with Xcode. Clicked the play button. It said "build succeeded", but I did not find the newly generated app(or anything else) in the folder? It seemed nothing happened.
<img width="1394" alt="WX20200925-082511@2x" src="https://user-images.githubusercontent.com/17448419/94213443-54c1d880-ff09-11ea-85d6-bf671277f837.png">

I clicked the play button a few more times, but still nothing new was generated.

**Comment by imxieyi** [comment]
You should select the scheme `waifu2x-mac-app` or `waifu2x-mac-cli` based on what you need. You can find all schemes on the tool bar with `waifu2x-mac` button

**Comment by fisheva** [comment]
Great! Finally, the app came out. Thanks!
![iShot2020-09-25 17 56 45](https://user-images.githubusercontent.com/17448419/94257863-8913b400-ff5e-11ea-9ab7-3702fa4ab8c0.jpg)


A few more questions:

1,   I rummaged through all the waifu2x-mac-app options but didn't find the same setting options before conversion as on the website? How to set these options on the APP?
<img width="997" alt="WX20200925-175324@2x" src="https://user-images.githubusercontent.com/17448419/94256860-fd4d5800-ff5c-11ea-8788-d40bc529bc2b.png">

2, After the waifu2x-mac-app was built, can I delete the Xcode? Since Xcode's size is too large.

**Comment by imxieyi** [comment]
> 1, I rummaged through all the waifu2x-mac-app options but didn't find the same setting options before conversion as on the website? How to set these options on the APP?

These options was just added in 9eacfa5.

>2, After the waifu2x-mac-app was built, can I delete the Xcode? Since Xcode's size is too large.

Yes. I'll try to set up CI to provide pre-built binaries.
