### ISSUE TITLE
Build failed and Xcode error

### ISSUE THREAD

**Issue by LillySss** [imxieyi/waifu2x-mac#25]
Hi, thank you for upload the waifu app for Mac user...but I have some problems with it :( I tried to build it and it failed, also when I used the Xcode, the app wouldn't build and I keep getting the error messages..please help me :'( Thank you

Build failed:
<img width="569" alt="Screen Shot 2020-10-20 at 12 07 12 PM" src="https://user-images.githubusercontent.com/73156152/96545170-11714480-12d2-11eb-80c2-f4483b956f31.png">

Xcode error:
<img width="1397" alt="Screen Shot 2020-10-20 at 12 30 03 PM" src="https://user-images.githubusercontent.com/73156152/96545219-29e15f00-12d2-11eb-8fd6-b3bff76e7e42.png">

**Comment by imxieyi** [comment]
Did you use "download zip" instead of "git clone"?

**Comment by julianko13** [comment]
It's the issue of Xcode 12, please see the workaround here: [https://aiharasoft.com/wordpress/swift-tips/type-mlmodel-has-no-member-__loadcontents-error-on-xcode-12/](url)

**Comment by imxieyi** [comment]
Generated class is not used in this project. Disabled it.
