### ISSUE TITLE
Can't compile application with build.sh OR Xcode

### ISSUE THREAD

**Issue by HumerousGorgon** [imxieyi/waifu2x-mac#30]
Hey there! Trying to compile this myself, it won't work no matter what I do.

Attempting to compile in Xcode gives me this error inside of the Waifu2x.swift file:
Waifu2x.swift:203:9 The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

Attempting to compile using the build.sh file in terminal gives:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/31957201/211238695-d512fa32-f51f-4da3-9396-45d2c3bb1828.png">

I'm not sure what I'm doing wrong here, but nevertheless it isn't compiling.

Thanks!

**Comment by imxieyi** [comment]
Fixed. Feel free to re-open if it's still happening with the latest commit.

**Comment by HumerousGorgon** [comment]
Sorry to open again; I am having the same issue and a different issue...

Terminal still gives me this:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/31957201/211251813-61d4f0d6-3636-4d4d-9864-5c509557cc72.png">

Opening the project in Xcode see's it succeed in building but it won't let me run anything.
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/31957201/211251932-eea4c033-34f9-414d-9499-e5dc74295ce3.png">

Any ideas? Am I doing something wrong?

EDIT:
Nevermind, I'm dumb! Fixed it

**Comment by imxieyi** [comment]
The build script has been fixed in the latest commit.

**Comment by HumerousGorgon** [comment]
Seperate thing but do you know if it's at all possible to output a 16 bit image from this? Swift is capable of doing it but it's about what I need to change in the code to enable it to do so.

**Comment by imxieyi** [comment]
Basically what you need is to change [CGImage format](https://github.com/imxieyi/waifu2x-mac/blob/master/waifu2x-mac/Waifu2x.swift#L245) to 16-bit and then convert image to 16-bit instead of 8-bit in [out_pipeline](https://github.com/imxieyi/waifu2x-mac/blob/master/waifu2x-mac/Waifu2x.swift#L166).

Due to limitation of Core ML the output image will not be actual 16-bit. The output from Core ML is float16 (cannot be changed), which means maximum 10 bits precision. I don't think it's possible to store 10-bit images though.

**Comment by HumerousGorgon** [comment]
Should be as simple as changing imgData to UInt16 in the out_pipeline right?
Unfortunately I get errors appearing all over the shop when I do it.

At the end of the day, I really only need 10 bit precision. I've converted 10 bit video into 16 bit frames, need to upscale them but keep precision of 10 bit so that when I recompile it all together I don't get banding.

**Comment by imxieyi** [comment]
You should not use UInt16. Instead please increase size of UInt8 arrays.

If you need a solution as soon as possible you can try App Store version of [waifu2x](https://apps.apple.com/app/waifu2x/id1286485858). It supports 16-bit video processing ([tutorial](https://github.com/imxieyi/waifu2x-ios/wiki/How-to-process-videos-(Mac-App-Store-version)#examples)) via pipe with ffmpeg. Please note that it also suffers from float16 issue on Core ML.
