### ISSUE TITLE
If it will have an instrument panel, it would be fine.

### ISSUE THREAD

**Issue by PlutoNameless** [imxieyi/waifu2x-mac#4]
I can't control the parameters and noise reduction of the amplification, and even which training model it uses is not clear.

There is also a small problem. Under 10.14, I can't see it working or occupying system resources in the istar menu.

**Comment by imxieyi** [comment]
This GUI app is just for demo purpose, i.e. the same use as the one from waifu2x-ios. You should try to modify the source code to change the model. You can also try the CLI version which supports several parameters.

I have upgraded to 10.14 and it still works fine. Core ML can use GPU as backend. In this way it is normal that CPU utilization is low. If it just produces nothing, can you run it in xcode and paste console output here?

**Comment by imxieyi** [comment]
The config pane for parameters was added in 9eacfa5. On the latest macOS Catalina and Big Sur iStat Menus shows GPU being used.
