### ISSUE TITLE
Update the linking of CLI version

### ISSUE THREAD

**Issue by chargeflux** [imxieyi/waifu2x-mac#5]
Hi,

I believe I figured out how to bundle the CLI version with the app itself such if you go into `waifu2x-mac-app.app/Contents/MacOS`, you can choose to launch `waifu2x-mac-app` which is the GUI or `waifu2x` which is the CLI version. This ensures that the CLI version and GUI version are packaged together and the CLI doesn't need to be in the same directory as the frameworks.

I can submit a PR for these changes. It involves copying CommandLineKit to the Frameworks directory of the .app directory and adding a search path for the CLI version to reference that. 

I also disabled installing the CLI version to `/usr/local/bin` and making sure the CLI version is only inside the App bundle since the executable in `/usr/local/bin` will fail because of missing frameworks.

**Comment by imxieyi** [comment]
I don't think it makes much difference from current method. Mac app is fundamentally bundled in a directory. One possible optimization is to write a wrapper script for `/usr/local/bin` which can pass arguments to the real `waifu2x` executable.

**Comment by chargeflux** [comment]
The Mac app is bundled in a directory but the CLI executable is completely separate and is currently not bundled with the Mac app. 

If I build/archive just the Mac GUI app, it doesn't have a CLI interface. If I archive the CLI version it doesn't work since the frameworks are not in the same directory as the CLI executable. If I build the CLI version the 2 frameworks it is dependent on is in the same directory and works.

From a user and release's point of view, I think it would make sense if the CLI and GUI app are packaged together in a .app directory and all dependencies for both are in that .app directory and linked to it. Right now, the CLI executable is unusable if you don't have frameworks in the same directory and I don't think that is the right approach.

It would be easier to have everything in the .app bundle and if the user wants to use the GUI version nothing changes. if the user wants to use the CLI version, they can go into the app directory (`waifu2x-mac-app.app/Contents/MacOS`) and launch CLI, which will work 100% since the frameworks it links against is in the same .app directory in `waifu2x-mac-app.app/Contents/Frameworks`. If the user doesn't want to go into the .app directory to use the CLI version, then the user can do an alias to the CLI executable and place it in `/usr/local/bin`

**Comment by imxieyi** [comment]
Currently the GUI version does not support choosing different models. It would confuse user if the CLI version is packed into it. I will try to improve the UI and try embedding CLI version into app bundle if I have time. By the way, feel free to open a PR so that I can refer to your solution.

**Comment by chargeflux** [comment]
I am not sure what you mean "choosing different models" but I am guessing you mean offering the user option of using the GUI or CLI? I don't think such an option is necessary if that is what you mean. Regular users would use the GUI  app as-is like it is right now by double-clicking on `waifu2x-mac-app.app`. Others users interested in more control or scriptability can go into the app bundle and use the CLI binary executable `waifu2x`. Launching the app regularly would be irrelevant to the CLI executable in my solution.

I will submit a PR to give you my proposed solution.
