### ISSUE TITLE
Multi-threading option?

### ISSUE THREAD

**Issue by akatsuki** [imxieyi/waifu2x-mac#7]
I tried to use the CLI version and it has great speed.
But it uses only single thread.
ActivityMonitor.app shows it uses only 100% (other multi thread app uses 400 - 800% to conversion)
so I wander it has -j option (it uses for multi threading option at other waifu2x) to be more speed.

Unfortunately, Idk about the Metal and CoreML feature than you.
If you don't annoy with this order, please add new feature for choosing multithread.

Thank you for your great job 👍

**Comment by imxieyi** [comment]
Core ML generally runs on GPU instead of CPU. CPU is only used to feed image data in sections, which does not affect overall speed much.
