### ISSUE TITLE
Only the iGPU is used

### ISSUE THREAD

**Issue by sfslowfoodie** [imxieyi/waifu2x-mac#8]
Despite the Automatic graphics switching being disabled, only the UHD 630 iGPU resource on my MBP is being used, while the 560X usage stays at 0%. App compiled on Xcode 10.1. Is there any code/Xcode change necessary in order to enable the 560X usage?

**Comment by sfslowfoodie** [comment]
I should add that my MBP is running Mojave 10.14.2

**Comment by imxieyi** [comment]
Although Core ML already provides [MLModelConfiguration](https://developer.apple.com/documentation/coreml/mlmodelconfiguration) to choose backend between CPU and GPU, there is no configuration to select which GPU to use.

If you really want to use AMD GPU, you can consider reimplement using Metal Performance Shaders. You can select which GPU to use with MPS using [MTLCopyAllDevices()](https://developer.apple.com/documentation/metal/1433367-mtlcopyalldevices). As for this you can refer to another of my project [CoreML-MPS](https://github.com/imxieyi/CoreML-MPS).

**Comment by sfslowfoodie** [comment]
Thanks for the reply. There appears to be an untapped potential, even the 560X could prove to be 2 to 3 times faster than the anemic 630 iGPU. I understand right now only Apple could decide to implement an improved GPU resource utilization strategy for Core ML tasks.

**Comment by sfslowfoodie** [comment]
As it turns out, the 10.14.3 Mojave update fixes the issue, picking up the correct 560X GPU for the Core ML tasks, even with Automatic graphics switching turned ON.
The gain in speed is impressive!
4kx4k to 8kx8k 2X upscale juicy stats:
- (macOS 10.14.2) on MBP 15" 2018 iGPU UHD 630: 259.8s
- (macOS 10.14.3) on MBP 15" 2018 Radeon 560X: 37.5s (NICE!!)
For reference:
- (iOS 12.1.3) on iPhone XS Core ML: 151.2s
- (iOS 12.1.3) on iPhone XS MPSCNN: 81.4s (NICE!!)

**Comment by imxieyi** [comment]
Turned out to be an OS-related issue and has been fixed in 10.14.3.
